============================================
''' Testing for 7-base_geometry.py '''
============================================
''' TESTTING WITH the following... '''

# python3 -m doctest -v ./tests/file_name.txt

======================================
''' Importing TEMPLATE function''''
======================================
>>> MyList = __import__('1-my_list').MyList
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

==============
SUCCESS CASES
==============


Category 1
==========

Test 1:
>>> my_list = MyList([1, 4, 2, 3, 5])
>>> my_list.print_sorted()
[1, 2, 3, 4, 5]
>>> print(my_list)
[1, 4, 2, 3, 5]

Test 2:
>>> my_list = MyList([1, -3, 4, 2])
>>> my_list.print_sorted()
[-3, 1, 2, 4]

Test 3:
>>> my_list = MyList()
>>> my_list.print_sorted()
[]

Test 4:
>>> my_list = MyList()
>>> my_list.append(1)
>>> my_list.append(4)
>>> my_list.append(2)
>>> my_list.append(3)
>>> my_list.append(5)
>>> print(my_list)
[1, 4, 2, 3, 5]
>>> my_list.print_sorted()
[1, 2, 3, 4, 5]
>>> print(my_list)
[1, 4, 2, 3, 5]


Test 5:
>>> bg = BaseGeometry()
>>> bg.integer_validator("my_int", 12)
>>> bg.integer_validator("width", 89)


==========================
CASES THAT SHOULD NOT WORK
==========================

Category 2
==========

Test 1
>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented

Test 2
>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
TypeError: name must be an integer

Test 3
>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
ValueError: age must be greater than 0

Test 4
>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
ValueError: distance must be greater than 0

Test 5
>>> bg.integer_validator("name")
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

Test 6
>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Test 7
>>> bg.integer_validator([])
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'
